### ISSUE TITLE
[BUG] Ammoboxes mass bug report

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#101]
**Short Description**
Bug 1) Ammoboxes disable themselves due to being underweight. Could be caused by the round loading before the weight check.

Bug 2) Refill crates don't work. They contain no ammo, don't refill anything, don't display anything when you look at them, and can't be undone.

Bug 3) When ammoboxes are looked at with the visclip tool they turn invisible

**Screenshots (Optional)**
Bug 1) https://i.imgur.com/H45QpEw.png
https://i.imgur.com/S0HrMbe.gif

Bug 2) https://i.imgur.com/Xo6rKDe.jpg
https://i.imgur.com/wKRPnlm.png

Bug 3)
https://i.imgur.com/ucqBFhl.gif

**Comment by shadow7483147** [comment]
Visclip tool doesn't really apply here unless you can confirm that it's only ammo boxes that it affects.
I've downloaded a tool off the workshop that makes props invisible when you aim off of them in the exact same way

**Comment by DynamX767** [comment]
It is only ammo boxes. Visclip doesn't do that to any other prop or entity.

**Comment by TwistedTail** [comment]
Number 2 was fixed on 0017518. I'll check the other ones.

**Comment by TwistedTail** [comment]
Fixed number 3 on 437057a. Visual Clip and scalable entities use the same function, ENT:EnableMatrix, although for different purposes. Visual Clip seems to use it to "hide" the entity, while the scalable entity base uses it to visually scale entity. Along with some messed up logic, this was causing the entity to remain hidden at all times.

**Comment by TwistedTail** [comment]
Fixed number 1 on 863c215. It was the Weight tool's fault.
