### ISSUE TITLE
[BUG] Killicon lua errors

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#102]
Was noticing these in my server errors log.
[ERROR] addons/acf-3/lua/acf/shared/killicons.lua:59: attempt to concatenate field 'Class' (a nil value)
  1. v - addons/acf-3/lua/acf/shared/killicons.lua:59
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by thegrb93** [comment]
[ERROR] addons/acf-3/lua/acf/shared/killicons.lua:59: attempt to concatenate field 'Class' (a nil value)
  1. v - addons/acf-3/lua/acf/shared/killicons.lua:59
   2. unknown - lua/includes/modules/hook.lua:84
    3. TakeDamage - [C]:-1
     4. ACF_Damage - addons/acf-3/lua/acf/server/damage.lua:318
      5. ACF_HE - addons/acf-3/lua/acf/server/damage.lua:209
       6. ACF_BulletEndFlight - addons/acf-3/lua/acf/shared/rounds/he.lua:124
        7. ACF_DoBulletsFlight - addons/acf-3/lua/acf/server/ballistics.lua:264
         8. ACF_CalcBulletFlight - addons/acf-3/lua/acf/server/ballistics.lua:134
          9. ACF_CreateBullet - addons/acf-3/lua/acf/server/ballistics.lua:87
           10. Detonate - addons/acf-missiles/lua/entities/acf_explosive/init.lua:238
            11. Detonate - addons/acf-missiles/lua/entities/acf_missile/init.lua:438
             12. ACF_Damage - addons/acf-missiles/lua/entities/acf_missile/init.lua:547
              13. ACF_HE - addons/acf-3/lua/acf/server/damage.lua:209
               14. ACF_BulletEndFlight - addons/acf-3/lua/acf/shared/rounds/he.lua:124
                15. ACF_DoBulletsFlight - addons/acf-3/lua/acf/server/ballistics.lua:264
                 16. ACF_CalcBulletFlight - addons/acf-3/lua/acf/server/ballistics.lua:134

**Comment by TwistedTail** [comment]
Related to missiles, they don't have a killicon or ENT.Class defined on them. There was a check missing to make sure ENT.Class was not nil, so that was producing this error. Fixed on eacc1b6.

**Comment by thegrb93** [comment]
Thx
