### ISSUE TITLE
[BUG] Lack of piledrivers in ACF

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#106]
**Short Description**

Piledrivers are currently not useable in ACF3 like they should be. This is a long standing bug as it was also an issue in ACF2 that carried over into ACF3. Piledrivers do not show up in any of the spawn tabs. 

**Console Error Logs (Optional)**

`Couldn't find acf component 'piledriver' .. (x235)`

**How to Reproduce (Optional)**

Open gmod and try to spawn a piledriver. You will notice that they do not show up in the menu.

**Screenshots (Optional)**

https://i.imgur.com/IcgGmIp.png

**Additional Information (Optional)**

This issue is being caused by a lack of piledrivers, only fix is to add piledrivers.

**Comment by Goodva** [comment]
absolutely discusting, its been 5 hours and they have not fixed this absolutely critical bug, this is very, VERY bad thing not to fix this bug, i cant beli

**Comment by PolySteam** [comment]
First they remove minmax, now they refuse to add piledrivers. Vile and disgusting behaviour.

**Comment by Goodva** [comment]
the issue should be closed, piledrivers have been added

**Comment by TwistedTail** [comment]
Not until they get merged to master.

**Comment by Goodva** [comment]
understandable, my bad

**Comment by TwistedTail** [comment]
Added on 6e6f23d, merged to master on 40a67db.
