### ISSUE TITLE
[BUG] [DEV] New brake code causing rare but severe lag

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#126]
**Short Description**

Rarely (only experienced it twice so far) the new brake code causes immense lag on my server. The server would begin lagging, I'd start the profiler, and it was showing that most of it was coming from `ENT:ApplyBrakes()` in `/entities/acf_gearbox/init.lua`. The lag stops immediately once the gearbox or whole contraption is removed, so I am fairly confident the profiler is correct.

There are no console errors associated with this lag.

**How to Reproduce**

I genuinely have no idea what triggers this, although both times this has happened it was with the same person's vehicle. Will ask them to provide a copy if necessary. Both times the vehicle was inactive (the builder was working on it at both times).

**Screenshots**

During the lag:
![image](https://user-images.githubusercontent.com/21130637/94878964-deebce80-042c-11eb-801a-ceb524ed6574.png)

After removing (and then respawning) the contraption in question:
![image](https://user-images.githubusercontent.com/21130637/94878977-ea3efa00-042c-11eb-8ad7-f666066123c7.png)

**Comment by Stooberton** [comment]
![image](https://user-images.githubusercontent.com/5084958/94880535-cf6a8680-0428-11eb-85fb-920d039d9524.png)

@LiddulBOFH
