### ISSUE TITLE
[BUG] Rounds ricochet until they run out of energy on specific brush materials

### ISSUE THREAD

**Issue by PolySteam** [Stooberton/ACF-3#128]
**Short Description**

Happens with AP,APFSDS,APDS,APHE. Rounds will ricochet until they run out of energy on things like windows, ventilation ducts, etc that are part of the world. Have not been able to reproduce it with prop_physics.

**How to Reproduce**

Fire any AP derived round at a specific brush material such as the tower window on gm_vyten.

**Video**
https://puu.sh/GyWtx/8a61850746.mp4

**Comment by Stooberton** [comment]
Fixed in the world penetration overhaul 7475ecbfb935a086bdce96e39904cfe9d3d3c82c
