### ISSUE TITLE
[SUGGESTION]Flare launchers should not count towards ACF gun limit

### ISSUE THREAD

**Issue by Uberdude9001** [Stooberton/ACF-3#130]
**Short Description**
Smoke launchers don't count towards the limit and instead have their own, similarly flare launchers are a purely defensive weapon.

**Comment by TwistedTail** [comment]
Added on https://github.com/TwistedTail/ACF-3-Missiles/commit/3f7e881db35965ed004e4789caa7d7d1d2c178c9, merged to master on 40a67db. Their limit will now be controlled by the `sbox_max_acf_flarelauncher` convar.
