### ISSUE TITLE
[BUG] Lots of error spam from bullets with pasted tank

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#135]
10/23/2020 - 23:05:42: Lua Error: 
[acf-3] addons/acf-3/lua/acf/base/util/sh_util.lua:159: bad argument #1 to 'pairs' (table expected, got userdata)
  1. pairs - [C]:-1
   2. TraceF - addons/acf-3/lua/acf/base/util/sh_util.lua:159
    3. DoBulletsFlight - addons/acf-3/lua/acf/server/ballistics.lua:214
     4. CalcBulletFlight - addons/acf-3/lua/acf/server/ballistics.lua:118
      5. v - addons/acf-3/lua/acf/server/ballistics.lua:149
       6. unknown - lua/includes/modules/hook.lua:84

**Comment by TwistedTail** [comment]
Fixed on 8a6d63e. One of the bullets was probably receiving a entity filter instead of a table, which is what the function expected the trace filter to be. ACF.TraceF will now properly deal with these cases.
