### ISSUE TITLE
[BUG] Guns' bullets don't exit from the barrel?

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#137]
This weapon I made before now causes me to suicide even with the dome removed. I'm guessing the bullets are somehow hitting me?

https://www.youtube.com/watch?v=g_ycf7gKz28

**Comment by thegrb93** [comment]
![20201029002217_1](https://user-images.githubusercontent.com/6713261/97525325-e5faf380-197c-11eb-82b0-8e6657fa89d8.jpg)

**Comment by thegrb93** [comment]
(that's not me in the chair btw)

**Comment by TwistedTail** [comment]
I suppose the `ENT:BarrelCheck` function on weapons is hitting something that doesn't belong to the same owner as the weapon itself.

https://github.com/Stooberton/ACF-3/blob/8a6d63e4c8e47b775325f9d74e954f6d60e81210/lua/entities/acf_gun/init.lua#L342-L358

Maybe you could try printing the entity it hit before the HitPos is returned? I don't really know why this kind of stuff is happening in the first place, as the same filter is later used on the bullet so I doubt it's hitting the weapon.

**Comment by thegrb93** [comment]
It seems to be the owner itself they are hitting

**Comment by thegrb93** [comment]
I just logged off, but I can check tomorrow if you think that's wrong.

**Comment by thegrb93** [comment]
Players in seats are solid on my server so they can take damage.

**Comment by TwistedTail** [comment]
I assume that's the reason why, players don't own their own player entity, so the check on line 351 is failing.

**Comment by thegrb93** [comment]
Thanks 👍

**Comment by thegrb93** [comment]
This fix doesn't work if someone besides the owner is using it.

**Comment by thegrb93** [comment]
Just do `TraceData.filter = {self, self:GunUser()}` w/e the function to get gun user.

**Comment by TwistedTail** [comment]
It's already doing that on line 414

https://github.com/Stooberton/ACF-3/blob/2807c65ec618d269186dd0d4189cd0672901e2b0/lua/entities/acf_gun/init.lua#L414

which is later used on this condition

https://github.com/Stooberton/ACF-3/blob/2807c65ec618d269186dd0d4189cd0672901e2b0/lua/entities/acf_gun/init.lua#L349-L357

**Comment by TwistedTail** [comment]
Gotta assume it's ACF's fault, the list of entities it'll support is really short and does not include any entities from Starfall.

https://github.com/Stooberton/ACF-3/blob/2807c65ec618d269186dd0d4189cd0672901e2b0/lua/entities/acf_gun/init.lua#L242-L257

**Comment by thegrb93** [comment]
Yeah that's why. I'll just hook up a pod controller for now.
