### ISSUE TITLE
[BUG] Multifuel engines can't link to any fuel

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#138]
**Short Description**
After yesterday's multifuel engines accepting electric fuel fix, you can't link any fuel at all to multifuels.

**How to Reproduce (Optional)**

Link fuel to a multifuel engine

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/68765998/97788305-119cfa00-1b86-11eb-9fe8-6f06e9923e5b.png)
![image](https://user-images.githubusercontent.com/68765998/97788307-1366bd80-1b86-11eb-91c0-f42abee9ece1.png)

**Comment by TwistedTail** [comment]
Fixed on 3d87d70.
