### ISSUE TITLE
[BUG] ACF3 won't mount/load on Linux (both server & client, Linux distro independent)

### ISSUE THREAD

**Issue by RanchTheDeer** [Stooberton/ACF-3#140]
**Short Description**

When trying to load ACF3 by putting it in the addons folder, nothing happens. The game recognises it as a filesystem addon but does not mount any of the content, nor load any lua files from the addon. To get it to work, you have to manually merge the ACF3 files with the GarrysMod/garrysmod folder, at which point it loads and works just fine. though this is not ideal because it's messy and makes updating a pain in the backside.
Manually running lua/autorun/acf-loader.lua whilst the files are still present in the addons/ACF3 folder reports in the console that client, server or shared files were loaded, and again, nothing happens.

**How to Reproduce (Optional)**

- Install ACF3 as normal on an installation on Linux, then start the game (any branch)

**Screenshots (Optional)**

Not applicable

**Additional Information (Optional)**

- This issue is identical for both the Linux client and server.
- This issue seems to be exclusive to the Linux release of Garry's Mod as I recall it seems to work fine on Windows.
- I triple checked that I have my folders set-up correctly and it is indeed correct, as it's the same as the other legacy addons that I use and, again, works just fine on Windows with the exact same setup.

Really wish I could shed some more light on this issue but I'm not terribly familliar with the inner workings of Garry's Mod's addon loading routines.

**Comment by CheezusChrust** [comment]
Give the addon folder a lowercase name. Linux GMod doesn't load addons that aren't all lowercase

**Comment by DynamX767** [comment]
it's because addons/ACF3 should be lowercase ie: addons/acf3

**Comment by RanchTheDeer** [comment]
That is the strangest yet most simple solution to a problem I've had in a long while.
Renaming the folder from ACF3 to acf3 fixed it right up! 
I'll keep that whole-uppercase rule in mind whenever I'm adding legacy addons to my game in future.

Thanks for the help! :3
