### ISSUE TITLE
[BUG] [Dev Branch] Ammo boxes get set to 50000kg if they can't hold at least one round

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#143]
**Short Description**

Ammo boxes too small to carry at least 1 round get set to 50000kg.

**How to Reproduce**

Spawn an ammo box for a large caliber cannon round or something and make it too small to hold at least one round.

**Screenshots**

![](https://i.imgur.com/7STeKmc.jpeg)

**Additional Information**

Discovered this when spawning some old tanks and noticed they were suddenly massively overweight.

**Comment by TwistedTail** [comment]
This was probably fixed on 6d590b6 in the dev branch. We'd need to confirm it though.

**Comment by CheezusChrust** [comment]
Tested just now and it seems to be fixed.
