### ISSUE TITLE
[BUG] Lack of tiny standalone electric 

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#145]
**Short Description**
So this issue has the same basic premise as the missing piledrivers issue, which i may add still has not been resolved. As you can see, there is a complete lack of the tiny electric motor after the new menu was added last night. 

**How to Reproduce (Optional)**
Try to spawn tiny electric motor, you will find that you can't

**Screenshots (Optional)**
https://cdn.discordapp.com/attachments/684151115893440571/779435461798133870/unknown.png

**Additional Information (Optional)**

All jokes aside this engine was actually useful please readd it

**Comment by TwistedTail** [comment]
Oops. Fixed on 3d87d70.
