### ISSUE TITLE
[BUG] [Dev Branch] ACF entities unweld themselves when updated

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#148]
**Short Description**

When an ACF entity is updated, it loses any weld constraints it had.

**How to Reproduce**

Spawn an ACF engine or gearbox, weld it to the ground or a prop. Update said engine or gearbox and the weld is gone.

**Additional Information**

This seems to only happen with weld constraints specifically.

**Comment by TwistedTail** [comment]
It seems to be a problem related to how constraints are saved, noticed that it happened once to me due to the constraint table missing it's Type value on one of the entries. It's also a bit inconsistent from what I could tell, I couldn't replicate it on my server with the given instructions, so it's definitively an interesting issue.

**Comment by TwistedTail** [comment]
Added something on 07bd535 that should help with this issue. Noticed certain stuff such as weld latches would create a constraint but change their `Type` value to an empty string, which could actually break the `ACF.RestoreEntity` function. Still no luck at trying to replicate this issue with regular welds.

**Comment by CheezusChrust** [comment]
Tested again just now on the procedural-armor branch (which I assume is based off dev?) and it's still happening - video https://streamable.com/cg77ot

**Comment by TwistedTail** [comment]
Pretty sure I got it right this time on c58f8be. Constraints with the world seem to be restoring just fine now. It should now be able to deal with wire hydraulics aswell.

Not gonna close it instantly, since as you mentioned it's a really inconsistent issue.
