### ISSUE TITLE
[SUGGESTION] Rocket pod for the Russia Attack Helicopter.

### ISSUE THREAD

**Issue by ddubaa99** [Stooberton/ACF-3#149]
**Short Description**

70mm x 7 rocket pod is not enough.
So, I want to more variation rocket pod.

B-8V20A: 80mm x 20 !!!
UB-32    : 57mm x 32 !!!

**References (Optional)**

https://weaponsystems.net/system/183-80mm+S-8+aerial+rocket
![image](https://user-images.githubusercontent.com/61778900/100038533-5d6e5680-2e47-11eb-81b1-0a616246121d.png)
![image](https://user-images.githubusercontent.com/61778900/100038597-6a8b4580-2e47-11eb-9218-9797e7d7fee8.png)

**Comment by ghostehis1** [comment]
This is already planned, along with several other launchers like the:
+ B-8V7 / S7
+ M261 and 260
+ Matra F4 and F2
+ and their respective rockets. (S-8, Hydra/FFAR, SNEB)

The B-8-20 pod is already finished, here's some screenshots of it:
![20201124125348_1](https://user-images.githubusercontent.com/5154367/100085426-b1336c80-2e54-11eb-8473-aea3b6c91e17.jpg)
![20201124125700_1](https://user-images.githubusercontent.com/5154367/100085431-b42e5d00-2e54-11eb-8ad2-18536f971b91.jpg)

**Comment by Goodva** [comment]
why would you reopen it
