### ISSUE TITLE
[BUG] Bug when you try to use the ACF Menu tool

### ISSUE THREAD

**Issue by kwiken210** [Stooberton/ACF-3#151]
**When I spawn in and click the ACF Menu in the toolbar it says an error and I _cannot_ use ACF-3 fully.**

**Console Error Logs**
[acf-3-master] addons/acf-3-master/lua/acf/client/sk_menu.lua:72: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Init - addons/acf-3-master/lua/acf/client/sk_menu.lua:72
    3. CreateFromTable - lua/includes/extensions/client/panel/scriptedpanels.lua:62
     4. func - addons/acf-3-master/lua/weapons/gmod_tool/stools/acfmenu.lua:52
      5. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
       6. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
        7. ActivateTool - lua/includes/modules/spawnmenu.lua:287
         8. Open - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:118
          9. Run - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:241
           10. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:11
            11. unknown - lua/includes/modules/concommand.lua:54

**Screenshot**
https://prnt.sc/vy8mco

**Comment by TwistedTail** [comment]
Make sure you don't have another version of ACF installed at the same time (nrlulz/ACF, ACE).

**Comment by kwiken210** [comment]
I had ACF-3 installed only, I had CSSContent too but I dont know if that conflicts. ACF-2 and ACE are working normally.

**Comment by TwistedTail** [comment]
What about ACF Missiles, are you using the correct version? Another reason could be you're using Bubbus/ACF-Missiles.

**Comment by TwistedTail** [comment]
This issue can no longer be tracked due to the changes on 40a67db. The menu was entirely replaced with a new one.
