### ISSUE TITLE
[BUG] Error on server load

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#160]
Getting this server error when the game loads.

[acf-3] addons/acf-3/lua/entities/base_scalable/init.lua:167: attempt to index field 'Player' (a nil value)
  1. v - addons/acf-3/lua/entities/base_scalable/init.lua:167
   2. Call - lua/includes/modules/hook.lua:84
    3. Paste - addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1179
     4. v - addons/advdupe2/lua/autorun/server/advdupe2_sv_init.lua:83
      5. unknown - lua/includes/modules/hook.lua:84

**Comment by thegrb93** [comment]
Looks to be from the dupe my server pastes on map load. I don't recall copying any ACF entities into it though.

**Comment by TwistedTail** [comment]
It's happening inside the `AdvDupe_FinishPasting` hook. I didn't consider dupes could be spawned by the server so this is why this bit of code is causing errors.
https://github.com/Stooberton/ACF-3/blob/c58ddabe9fec41f3832d8c09a00a36769f62f3ee/lua/entities/base_scalable/init.lua#L164-L178

**Comment by TwistedTail** [comment]
Fixed on 978ea30.
