### ISSUE TITLE
[BUG] Various models are not to scale

### ISSUE THREAD

**Issue by Stooberton** [Stooberton/ACF-3#182]
**Short Description**

`models/autocannon/autocannon_50mm.mdl` is roughly 70mm
`models/machinegun/machinegun_40mm_compact.mdl` is roughly 60mm
`models/autocannon/semiautocannon_45mm.mdl` is roughly 60mm

**Comment by LiddulBOFH** [comment]
Engines are also all over the place, same with gearboxes, would need to rescale everything and follow a single stepping scale (or alternatively make everything fully scalable)
