### ISSUE TITLE
[SUGGESTION] Changing Electric engines fuel tanks weight to smaller

### ISSUE THREAD

**Issue by SpringCegla** [Stooberton/ACF-3#189]
If it is possible please change weight of electric engines fuel tanks to slightly higher than diesel engine tank, as of right now they weight alot. To be precise electric fuel tanks are three times heavier than diesel fuel tanks which is kinda weird.

**Comment by Stooberton** [comment]
Weird in what way? Batteries are significantly heavier than fuel tanks in reality. Lithium-Ion batteries have an energy density of roughly 0.3 MJ/kg versus 47.5 MJ/kg. For the same amount of energy you will have to expend more weight in battery.

**Comment by SpringCegla** [comment]
.... sorry i forgot that they are Lithium-Ion in acf.
