### ISSUE TITLE
[BUG] Firing at fuel tanks causes no explosions/leaks

### ISSUE THREAD

**Issue by arthritisguy** [Stooberton/ACF-3#191]
**Short Description**

Firing at fuel tanks with any rounds causes no leaks. ACF combat mode was changed to check if the combat mode was the issue.

**Branch and Version**

Latest Master Branch

**How to Reproduce (Optional)**

Spawn in a fuel tank, the kind that gets linked to engines. Shoot at petrol or diesel tank with virtually any munition. Be sure there are no ammo boxes nearby to explode.

**Additional Information (Optional)**

Tested with all munitions and all sizes. Fuel tanks never leaked or exploded. Gmod has been restarted.

**Comment by PolySteam** [comment]
Only reproduced with diesel. Petrol and Electric explode.

**Comment by arthritisguy** [comment]
hmm, maybe I'll figure out if its an addon conflict

**Comment by arthritisguy** [comment]
fixed when I restarted gmod for the 3rd time.
