### ISSUE TITLE
[SUGGESTION] [ACF Survey] Scaling Components

### ISSUE THREAD

**Issue by DaAstronautical** [Stooberton/ACF-3#2]
**Raw Suggestions**
instead of set calibers make it a slider
Scalable entities, generic missiles instead of specific ordnance

**Interpretation**
Components that are scaled with a slider instead of fixed calibers.

**Comment by Stooberton** [comment]
This is definitely something we've talked about and plan to do almost verbatim.

**Comment by Stooberton** [comment]
Scalable guns and ammo crates have been added. More to come?
