### ISSUE TITLE
[SUGGESTION] Add E2 functions to get Ammo Count/Capacity

### ISSUE THREAD

**Issue by marchcain** [Stooberton/ACF-3#201]
**Short Description**

Title pretty much sums it up, E2 functions to get how much ammo is left in a crate and the capacity of the crate.

**Comment by LiddulBOFH** [comment]
They do exist, however badly spread out, could be more finely grouped with a single ammo function that works across multiple entities properly
- Gets rounds in a crate
https://github.com/Stooberton/ACF-3/blob/78805cbfa8a25e6d9e5282c2a9ac4688b5beda37/lua/entities/gmod_wire_expression2/core/custom/acffunctions.lua#L936
- Gets rounds in the magazine of a weapon, also has MagSize to go with it
https://github.com/Stooberton/ACF-3/blob/78805cbfa8a25e6d9e5282c2a9ac4688b5beda37/lua/entities/gmod_wire_expression2/core/custom/acffunctions.lua#L904
- Gets all of the *ACTIVE* ammunition available to a weapon, theres also a Total variant which gets all rounds totally available 
https://github.com/Stooberton/ACF-3/blob/78805cbfa8a25e6d9e5282c2a9ac4688b5beda37/lua/entities/gmod_wire_expression2/core/custom/acffunctions.lua#L1092

When I move on from other stuff I'll look into merging many of these to just a few functions, no need for many of these extra functions
