### ISSUE TITLE
[SUGGESTION] Change throttle input so 1 or 100 is maximum

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#202]
Make using engines easier for direct linkage to pod controllers and things.  1 or 100 is maximum, 2-99 works like normal.
I don't think anyone is running an engine at 1%, shouldn't be an issue. If it is, add it as a clientside option or such to enable/disable 1 being max throttle (on by default for new people I suppose)

**Comment by solomondog50** [comment]
> unnecessary level of complexity.

you just start at two instead of zero

**Comment by Alexandre425** [comment]
> 
> 
> > unnecessary level of complexity.
> 
> you just start at two instead of zero

Which makes absolutely no sense. Just make it go from 0 to 1, makes it so a pod controller can be used standalone, and still allows for granularity in the throttle with a 10s fix in your control E2.

**Comment by solomondog50** [comment]
> Which makes absolutely no sense. Just make it go from 0 to 1, makes it so a pod controller can be used standalone, and still allows for granularity in the throttle with a 10s fix in your control E2.

I wasn't agreeing or disagreeing, more just stating that isn't unnecessarily complex fix

The only thing that would break is throttle control chips that range from 0-100, but it would not at all be hard to just divide the output by 100
I don't think it would be problem, since an input of 100 would be clamped to 1 and would work the same, which is how I think most (at least land based) vehicles behave

I don't think the change would have any significant effect on pre-existing vehicles

**Comment by Alexandre425** [comment]
> 
> 
> As I mentioned in the discord, I don't see why we cannot have both. Who uses 1% throttle? Could easily have it interpret any input from 0 to 1 or 0 to 100 simultaneously.
> 
> 0.25 -> 25%
> 25 -> 25%
> 0.75 -> 75%
> 75 -> 75%
> 1 -> 100%
> 100 -> 100%

Honestly that seems like a really bad solution. Doesn't make any sense, and the only reason for it to exist is for compatibility, which is absolutely trivial to update regardless, doubt it'd take more than 10s.

 0-1 is extremely simple, and solves any issue there might be. Any complaints can be redirected to updating your E2 controller and removing the `* 100`

**Comment by Stooberton** [comment]
Don't think this is really worth breaking builds over.

**Comment by Amplar** [comment]
the only thing it would break is someone using 1% throttle, which is extremely unlikely
