### ISSUE TITLE
[BUG] acf armor values

### ISSUE THREAD

**Issue by Sypher866** [Stooberton/ACF-3#205]
**Short Description**
I was building and set armour on some props to be 70mm and -80 dur, when I dup it, it just puts the props armour values back to their default weight values and everything I edit with the armour tool just gives me the same problem.
I was playing on acf3 dev.

**Branch and Version**
latest - 17 June 2021

**Console Error Logs (Optional)**
N/A

**How to Reproduce (Optional)**
N/A

**Screenshots (Optional)**
N/A

**Additional Information (Optional)**
I don't understand how this might be, but as I said it appears to work, and applies the values I have used in the menu of the acf armour tool but as soon as I dup and paste the thing.. It just seems like it didn't function and was giving false information.

I can safely assume it is related to the acf armour tool as other props that were edited previously do not inherit the problem and keep their changed armour values and mass as per usual, it is only props that I started to edit today, and it might fix itself but I haven't been able to even by changing server from acf3 dev to another random one and the problem persisted there as well.

**Comment by TwistedTail** [comment]
Fixed on b31fcf7.
