### ISSUE TITLE
[SUGGESTION] Additional features to Armor Tool

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#21]
It might be good to allow the armor tool to report more statistics and allow its use on anyones' vehicle. Report back mass, physical mass, maximum armor (maybe), armament, vehicle era (if applicable), prop/constraint count, e2 usage, and total physical entities.

**Comment by Stooberton** [comment]
I'm okay with knowing build quality data and mass, but not the armor of what you're looking at. I wouldn't even be opposed to disabling the wire popup if you don't own the entity you're looking at.
Many people are of the opinion that looking at someone else's armor is harmless but it leads to endless copycats and stagnation. A lot of the fun in ACF is developing things to gain an edge and having people copy you endlessly is not fun.

**Comment by Amplar** [comment]
fair enough, that reminds me of something- add a var to draw halos on acf stuff

**Comment by Stooberton** [comment]
wire_drawoutline 0

**Comment by Stooberton** [comment]
Taken care of in https://github.com/Stooberton/ACF-3/commit/3b62f8fd29348d28962cd5fbf1d4857998debee7
