### ISSUE TITLE
[SUGGESTION] Admin-only e2/sf functions

### ISSUE THREAD

**Issue by StrawWagen** [Stooberton/ACF-3#212]
**Short Description**

Add admin-only e2/sf functions.
Some ideas;
1. Functions that disable/enable receiving acf damage on a specific entity
2. Functions that modify acf properties of objects (armor, health, etc)

Would be pretty simple to implement, just have to lock the functions behind an IsAdmin() check.
These would be excellent for server-wide events where you don't want some specific entities to die horribly.

**Comment by Stooberton** [comment]
I like the idea but I don't think this should ship with ACF. Definitely a separate addon.
