### ISSUE TITLE
[SUGGESTION] Make way to clamp max thickness

### ISSUE THREAD

**Issue by wrefgtzweve** [Stooberton/ACF-3#221]
**Short Description**

It would be great to have a way to server side clamp the max amount of armor thickness you can have. This would be great for events where tanks can only have a max thickness of armor, to prevent people from using 5000mm armor tanks on servers that don't enforce ACF rules or to prevent people from armoring e2 chips to max thickness making them nearly indestructible. A simple convar or setting in the ACF menu would be perfect.

**Comment by Stooberton** [comment]
This would only deal with a single layer and incentivize, if one wanted more armor, to spam layers. Not sure if this is a good idea or within the scope of base ACF.

Perhaps, alternatively, a way could be added to hook into the armoring process so that it can be controlled with another addon.

**Comment by wrefgtzweve** [comment]
A hook would absolutely be great yeah

**Comment by wrefgtzweve** [comment]
Made a pr for it https://github.com/Stooberton/ACF-3/pull/229

**Comment by TwistedTail** [comment]
Pull request merged in bd045e0, closing.
