### ISSUE TITLE
[BUG] Weapons scaling incorrectly on duping them in

### ISSUE THREAD

**Issue by wrefgtzweve** [Stooberton/ACF-3#222]
**Short Description**

Getting Lua errors when duping in ACF weaponry, some of the weapons aren't scaling properly.

**Branch and Version**

Master but doesn't show up for some reason
![image](https://user-images.githubusercontent.com/69946827/139280343-3259edb2-e1ab-48d9-beba-6174bc186253.png)

**Console Error Logs (Optional)**

```
[acf-3] addons/acf-3/lua/entities/base_scalable/cl_init.lua:96: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. func - addons/acf-3/lua/entities/base_scalable/cl_init.lua:96
    3. unknown - lua/includes/extensions/net.lua:32
```

**How to Reproduce (Optional)**

https://p.teknik.io/Simple/L4En4 < the dupe file

**Screenshots (Optional)**

![image](https://user-images.githubusercontent.com/69946827/139280779-e568b401-f956-4053-80f7-317da1f59746.png)

**Comment by TwistedTail** [comment]
Entirely rewrote the scalable base in d7aeacd. If everything works as intended, this shouldn't happen anymore. Feel free to reopen this issue or create a new one if any problem surfaces.
