### ISSUE TITLE
Everything is an error

### ISSUE THREAD

**Issue by Jaycey64** [Stooberton/ACF-3#223]
Hello, I've recently got ACF 3 and the missile pack, but I can't see anything, I've taken some screenshots to show the problem, and yes I've installed it properly
![20211031214004_1](https://user-images.githubusercontent.com/80467027/139755143-1f148ed3-3b67-476d-955f-d95642da7cee.jpg)
![20211031214119_1](https://user-images.githubusercontent.com/80467027/139755151-a5233ad8-8a4b-4af1-983b-4f55ef62ac57.jpg)
.

**Comment by Stooberton** [comment]
1. Ensure you do not have any ACF content from the workshop. ACF 3 is not on workshop (yet).
2. Delete all ACF content from `garrysmod/garrysmod/addons`
3. Follow the installation guide here: https://github.com/Stooberton/ACF-3#manually

**Comment by Stooberton** [comment]
You can get better with diagnosing your issue in the discord server: https://discord.gg/TgDWWwFA

**Comment by Jaycey64** [comment]
Ok thanks

**Comment by Jaycey64** [comment]
Also It says this when I join the server, idk if this will hel
![20211102071051_1](https://user-images.githubusercontent.com/80467027/139836260-fcf7c154-eea6-4956-88b8-d268ccac7ad7.jpg)
p

**Comment by Stooberton** [comment]
That's the servers version, as it says. Please refer to my previous comments for installation and further assistance.

**Comment by Jaycey64** [comment]
> That's the servers version, as it says. Please refer to my previous comments for installation and further assistance.

So, I have to get the servers version?
(And I did what you said from your previous comment.)

**Comment by Jaycey64** [comment]
Also, it turns out that only some weapons are errors for some reason, i made a new issue about that here #224
