### ISSUE TITLE
Some of the weapons are errors

### ISSUE THREAD

**Issue by Jaycey64** [Stooberton/ACF-3#224]
I got ACF And ACF MISSLES recently but a lot of the weapons in the menu are errors, Here are some screenshots.
![20211105212219_1](https://user-images.githubusercontent.com/80467027/140593344-a95ec6c3-7f8b-4fa8-ae55-0210fa67c28a.jpg)
![20211105212224_1](https://user-images.githubusercontent.com/80467027/140593345-e2c29863-2036-4120-b78e-e04336628668.jpg)
![20211105212226_1](https://user-images.githubusercontent.com/80467027/140593346-fbda6456-358f-4358-940c-b57dba9e4516.jpg)
![20211105212229_1](https://user-images.githubusercontent.com/80467027/140593347-a2733892-4986-4ae8-ba20-a787e2db8543.jpg)
![20211105212231_1](https://user-images.githubusercontent.com/80467027/140593348-b04d9f94-4fad-47d4-aa11-62654bf1489d.jpg)
![20211105212239_1](https://user-images.githubusercontent.com/80467027/140593349-2f6cdfe0-2835-4f70-b1be-ae36806c19ff.jpg)
![20211105212244_1](https://user-images.githubusercontent.com/80467027/140593351-490538b1-2598-49e0-80d1-a79495ccffb2.jpg)

**Comment by TwistedTail** [comment]
Make sure you have ACF3 and ACF3 Missiles properly installed on your client.

**Comment by Jaycey64** [comment]
I do, this is in a server btw.

**Comment by TwistedTail** [comment]
Yeah, the server seems to be fine. The errors are a fault on your side, you could try reinstalling ACF3 entirely to make sure. Make sure to follow Steve's tips on the other issue, it's either a conflict between similar addons or just a faulty install.

**Comment by Jaycey64** [comment]
Ok.

**Comment by Jaycey64** [comment]
Also btw, the server has a ACF addon from the workshop, I uninstalled that, but I'm not sure if that helped.

**Comment by Jaycey64** [comment]
I'm also pretty sure the version of acf they have is outdated, Because I have some features they don't have.

**Comment by TwistedTail** [comment]
Yeah, could also ask them to make sure they have ACF properly installed and update there aswell, same tips.

**Comment by Jaycey64** [comment]
ok
