### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [Stooberton/ACF-3#241]
**Short Description**

Torch SWEP will spam server logs with "No perms" every game think if you use it on something you don't own. Additionally the torch does not work on other people's stuff unless they grant you toolgun permissions.

**Branch and Version**

Main branch, latest version (Commit f91e4e6)

**Source code where this issue is occurring**

[https://github.com/Stooberton/ACF-3/blob/master/lua/weapons/torch/shared.lua](url)

**How to Reproduce (Optional)**

Just use the torch on anything you don't own. You won't be able to damage it with ACF and it will spam logs serverside.

**Additional Information (Optional)**

I'm unsure if the requirement of toolgun permissions is intended or not but I think it limits the torch's use cases. Realistically just doing ACF.Damage already runs the ACF damage hook so other addons/scripts can block it. Additionally CPPICanDamage would probably be a better alternative to CPPICanTool if having permission checks of some kind is still a wanted behavior.

**Comment by Stooberton** [comment]
I don't see any particular reason why healing/damaging things with the torch cares about PP. It's a weapon that heals and damages things. If things like safezones want to stop it, then that'll be handled internally in the damage.

**Comment by Stooberton** [comment]
Removed PP checks in 4f98c9a773469b6b0ed37c32015e58215973b844
