### ISSUE TITLE
[BUG] Error when spawning contraptions with acf components, with acf3 installed without prop prot

### ISSUE THREAD

**Issue by Mrleplayz** [Stooberton/ACF-3#244]
Done on the latest branch as of 1/30/2022 6:19 PM
Adv Dupe 2 acf related error
Spawning a vehicle with acf2 components on a singleplayer game running acf3 WITHOUT any prop protection addons spits out this error :

[AdvDupe2Notify]    Pasting...
[AdvDupe2Notify]    addons/acf-3/lua/acf/base/acf_globals.lua:352: attempt to index local 'Lookup' (a nil value)
[AdvDupe2Notify]    Finished Pasting!

once falco's prop prot is installed, it all works just fine

**Comment by Alexandre425** [comment]
You need a prop protection addon. Nadmod is recommended.

**Comment by TwistedTail** [comment]
Prop protection addons shouldn't be necessary, I'll take a look at this

**Comment by TwistedTail** [comment]
Been testing this on singleplayer with no prop protection and I can't replicate it, even with my old dupes. Are you sure you don't have any other ACF version installed that could be conflicting with it?

![image](https://user-images.githubusercontent.com/8784231/151716269-541b40cd-4510-4bfe-8389-88fbefa1cc91.png)

**Comment by Mrleplayz** [comment]
No other acf versions installed, acf3 i cloned from git with the github app straight to my addons folder, and obv there isn't any difference from downloading manually and through the app.

i just tested it again by removing nadmod's prop prot, reloading the game and attempting to spawn something saved with acf2 components. Yet again, the problem pops up

Could it be a cache thing? Something left over from acf2 in my game files?

**Comment by TwistedTail** [comment]
You could try with only ACF3 and Wire enabled on the server. If it doesn't happen in that case then it's most likely a conflict with another addon.

**Comment by Mrleplayz** [comment]
Just tried it with wire, acf3 and advdupe2 and it still happens.
There's some maps that load even though i'm not subbed to them on ws, from joining servers and whatnot, might be a whole host of other things like that aswell
I'm gonna try recloning acf3

It's not that big of a deal if it only happens to me, i mean i haven't reinstalled the game in about a year if not more.

**Comment by TwistedTail** [comment]
You could try running `menu_cleanupgmas`, maybe there's some leftover from addons you used to have that are still being loaded in your singleplayer session.

**Comment by TwistedTail** [comment]
Temporarily patched this issue with 899976d, it'll still throw a massive dump into your console with stuff I need to properly fix this issue. If this does happen, make sure to send it here.

**Comment by TwistedTail** [comment]
Tried changing the hook to register the players when they first spawn in 8be9699, for whatever reason `PlayerInitialSpawn` isn't being called for some people, which I assume is related to another addon.

**Comment by TwistedTail** [comment]
Closing after 5 months without updates.
