### ISSUE TITLE
[BUG] acf_armor entity can surpass 50 ton mass limit

### ISSUE THREAD

**Issue by TwistedTail** [Stooberton/ACF-3#248]
**Short Description**

ACF Armor entities are not verifying their mass won't exceed the Source Engine 50 ton limit when being created, leading to some plates being severely underweight because of this.

**Branch and Version**

Master, latest version (46c474b).

**How to Reproduce (Optional)**

When creating from the menu, move all the sliders to the maximum possible value. For a RHA plate with a size of 420x420 gmu, any thickness value above 56mm will always set its mass to 50t.

**Comment by Stooberton** [comment]
677475a2556c96abffaa5258baa042ccef1e7484
