### ISSUE TITLE
[BUG] Weapons are being unlinked from ammo boxes when duped.

### ISSUE THREAD

**Issue by bluemetaknight** [Stooberton/ACF-3#251]
When duped, weapons seem to be unlinking for no apparent reason, regardless of distance between gun and ammo. Happens in single player as well as multiplayer.

Master Branch

How to Replicate:
Literally just link a gun to an ammo crate, dupe both, and respawn it. Everything becomes unlinked.

**Comment by TwistedTail** [comment]
Fixed on c6e7679.
