### ISSUE TITLE
[BUG] Context menu options (remove, bodygroup, disable collisions) don't work on scalable entities

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#252]
**Short Description**

If you try to, for example, change the bodygroup of a scalable weapon, you'll get a console error and nothing will happen. Same goes for if you disable collisions or try to remove it.

**Branch and Version**

Latest version of master.

**Console Error Logs (Optional)**

```
gamemodes/sandbox/gamemode/shared.lua:241: attempt to call method 'IsWeapon' (a boolean value)
  1. Call - gamemodes/sandbox/gamemode/shared.lua:241
   2. Filter - lua/autorun/properties/collisions.lua:13
    3. Receive - lua/autorun/properties/collisions.lua:32
     4. func - lua/includes/modules/properties.lua:173
      5. unknown - lua/includes/extensions/net.lua:33
```

**Comment by TwistedTail** [comment]
Fixed on 81e4d2e, ACF weapons used a flag called ENT.IsWeapon. Since they're scalable entities that use the custom __index metamethod, said flag was getting priority over the ENT:IsWeapon method.
