### ISSUE TITLE
[BUG] Inconsistency in returns of acfName() & acfNameShort() functions between ACF2 and ACF3

### ISSUE THREAD

**Issue by QbixRube** [Stooberton/ACF-3#256]
Tested with 57mm APDS crates.

In ACF2, calling the acfName() function on the crate returns "57mmSA APDS"
The acfNameShort() function returns "57mmSA"

In ACF3, calling acfName() on the crate will return "57mm Semiautomatic Cannon Armor Piercing Discarding Sabot"
The acfNameShort() function returns "57mmSAAPDS"

**Comment by TwistedTail** [comment]
Under what conditions is it not working? I'm testing it right now and it works like intended.

**Comment by TwistedTail** [comment]
Good to mention aswell, are we talking about the E2 or the SF function?

**Comment by QbixRube** [comment]
In Expression 2, On further testing, I mustve mucked something up on my first go since now it works on the test rig, however my E2 which worked with acf2 now doesn't work with acf3 so an inconsistency between the acf*() functions is still somewhere there. Apologies, should've been more thorough.

If you want, I can let you know what it is once I fully debug it, but I don't think its as serious as acfActive() being broken.

**Comment by QbixRube** [comment]
Or if it even warrants being fixed.

**Comment by TwistedTail** [comment]
If it's related to missing functions, feel free to open a suggestion.

> If you want, I can let you know what it is once I fully debug it, but I don't think its as serious as acfActive() being broken.
> Or if it even warrants being fixed.

It's up to you then, you're free to report your concerns. Someone might stumble on the same problem in the future so I don't really mind having to fix it.

**Comment by QbixRube** [comment]
I believe I've narrowed down the issue to the acfName() and acfNameShort() functions.

I've tested this with a 57mm APDS crate.

In ACF2, calling the acfName() function on the crate returns "57mmSA APDS"
The acfNameShort() function returns "57mmSA"

In ACF3, calling acfName() on the crate will return "57mm Semiautomatic Cannon Armor Piercing Discarding Sabot"
The acfNameShort() function returns "57mmSAAPDS"

**Comment by TwistedTail** [comment]
> In ACF2, calling the acfName() function on the crate returns "57mmSA APDS"
I feel like I should actually change `acfNameShort()` to return it like this, it's much easier to read. However, I don't feel like this is readable enough to be the "full name" of an ammo crate, it doesn't really tell you much unless you know what you're reading.

> The acfNameShort() function returns "57mmSA"
I changed this one back then because it's misleading, why is an ammo crate returning just the ID of the weapon it can be loaded into?

**Comment by QbixRube** [comment]
This seems like a good solution, having some consistency between acf2 & acf3 like this makes it much easier to update acf2 chips which use these functions. I've mainly used it for HUD stuff and ammo belting, so the whitespace being there saves some string manipulation stuff or using other functions with some concatenation. 

This change would make the acf2->acf3 transition smoother for some people, just slightly easier to fix broken chips. However it might effect acf3 chips that use acfNameShort(), depending on how they've used it. 

In my case I didn't have to fix much once I actually debugged the issue, just change the inputs I was using in a UDF. That being said, people who don't write their own chips might not have the same experience so these kinds of changes might be more of a brick wall for them.

**Comment by TwistedTail** [comment]
Changed on f501db5.
