### ISSUE TITLE
[BUG] SV error attempt to call field 'GetBranch' (a nil value)

### ISSUE THREAD

**Issue by wrefgtzweve** [Stooberton/ACF-3#259]
**Short Description**

Getting this server side error, started happening only recently and always happens twice in a row. Happens on startup.

**Branch and Version**

Master

**Console Error Logs (Optional)**

server side:
```
addons/acf-3/lua/acf/base/version/sv_version.lua:59: attempt to call field 'GetBranch' (a nil value)
```

**Comment by TwistedTail** [comment]
That's weird. Make sure the [shared version file](https://github.com/Stooberton/ACF-3/blob/master/lua/acf/base/version/sh_version.lua) exists and isn't corrupted or something. That function should be defined when it gets called by the serverside.

**Comment by wrefgtzweve** [comment]
Haven't had it recently, might've been caused due to bugs by another addon. Closing this for now.
