### ISSUE TITLE
[BUG] Brakes are useless after last update

### ISSUE THREAD

**Issue by TheLight91** [Stooberton/ACF-3#262]
**Short Description**

As the title says, brakes are now either super weak on some tanks (tried even putting brake multiplier to 10k from the usual 25) or make the wheels spazz when staying still on my truck. (Used to work fine before the update, very strong brakes without locking)

**Branch and Version**

Master Branch, latest version.

**Comment by TwistedTail** [comment]
How heavy are your wheels? Also, value gets clamped between 0 and 100.

**Comment by TheLight91** [comment]
Wheels on the tank are 300kg each, on the truck 200 I think.

**Comment by Alexandre425** [comment]
#263 should fix it

**Comment by TheLight91** [comment]
Will test it now.

**Comment by TheLight91** [comment]
Just tested it, brakes are as useless as before, super weak.

**Comment by Alexandre425** [comment]
> Just tested it, brakes are as useless as before, super weak.

hasn't been merged yet chief

**Comment by TheLight91** [comment]
I manually changed the code to match you changes. Tanks brakes remain useless, truck now doesn't brake either, guess it doesn't spazz anymore thanks to that.

**Comment by TheLight91** [comment]
Just tested the newest commit that was merged to fix this problem.

Brakes are set at 10k, physical weight is 2k. All acf entities are parented, no armor, no gun. The physical parts are wheels and baseplate.


https://user-images.githubusercontent.com/40478437/159665588-80b3b673-be95-4f12-aa5e-0a97c4b102bb.mp4

**Comment by PolySteam** [comment]
I'm not sure what I'm supposed to look at here, the brakes clearly work in the video. If you want a sudden stop run a wire weld latch to your sprocket.

**Comment by TheLight91** [comment]
> I'm not sure what I'm supposed to look at here, the brakes clearly work in the video. If you want a sudden stop run a wire weld latch to your sprocket.

At 10k strenght (the max) they barely slow down a test tank with nothing on it and with a very small physical mass.

**Comment by Alexandre425** [comment]
https://user-images.githubusercontent.com/37046867/159724647-cbcdb4cc-6249-415b-bcfe-82ebb3349257.mp4

Here's the very same tank you gave me braking at 10k, on the latest dev branch. Not sure what you did wrong, but it's definitely not a brake issue.

**Comment by TheLight91** [comment]
Just tested with the Dev version and it is indeed fixed and working better than acf2's version ever was.

**Comment by Alexandre425** [comment]
Glad to hear it
