### ISSUE TITLE
Contraption weight check reads incorrectly on dupes with physclipped props. [BUG]

### ISSUE THREAD

**Issue by bluemetaknight** [Stooberton/ACF-3#270]
When using the ACF Armor Tool's weight check function, the chat box print will read incorrectly if  a contraption with physclipped props is checked after the contraption has been duped and respawned. 

[https://drive.google.com/file/d/1LzLllvneAcFLbWYsD_z9Vk-48jFmY9Kq/view?usp=sharing](url)
This picture shows the dupes weight being checked post spawn by clicking R on the non clipped prop. Weight reads 909 kg.

[https://drive.google.com/file/d/1Z91Mk8RAfA1orbazazdv6UrpRiWNuFV4/view?usp=sharing](url)
This picture shows the dupe being checked post spawn, but by clicking R on the physclipped prop. Weight now reads 722.6 kg.

[https://drive.google.com/file/d/1SA-A_j8cB3shZqjm6aez2KyT77tK0OvL/view?usp=sharing](url)
This picture shows the dupe being checked post spawn again but with spherical search and by clicking on the non clipped prop.

This seems to suggest that the mass for physclipped props isn't updated post spawn until they are looked at directly by the ACF Armor Tool, or by weight checking with spherical search. 

[https://drive.google.com/file/d/1AYE5j7wF7frROxVJtlTVr1lo8O4eAQvI/view?usp=sharing](url)

Here's a copy of the dupe in order to replicate the issue.

Branch: GitHub Master, most recent version.

**Comment by Stooberton** [comment]
Looking at the prop causes the prop's ACF data to update, which shows a different value. This indicates to me that something changes the mass _after_ ACF did when pasting.

My best guess:
- Prop spawned
- Dupe info applied (armor settings, mass, etc.)
- Physclip runs and changes the mass: `newMass = oldMass * newVolume/oldVolume`

**Comment by LeninCat** [comment]
saw this happen with my tank. 
tank's weight will change after running area weight check aswell

**Comment by Stooberton** [comment]
![image](https://user-images.githubusercontent.com/5084958/181124135-ec1e2397-8c26-4cd8-a845-54fb2fcc0517.png)

**Comment by Stooberton** [comment]
Fixed in a8d4909bf991cd30487cb584d6b85ac5fa086c0d
