### ISSUE TITLE
Gearboxes unlink their wirelink when updated [BUG]

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#273]
As it says on the tin, transfer cases and possibly others are unlinking wirelink to e2 after updating.

**Comment by TwistedTail** [comment]
Any more details on this? I don't really understand the issue.

**Comment by Amplar** [comment]
Wirelink a gearbox to an E2, and update the ratios on the gearbox. The wirelink will unlink.

**Comment by Stooberton** [comment]
Happens with guns and radars too... But not engines, interestingly. Doesn't require any actual settings to be changed, just causing an update breaks the wirelink.

**Comment by Stooberton** [comment]
Calling `WireLib.AdjustInputs` is breaking the wirelink when an entity is updated. Wiremod bug/inconsistent behavior since wires aren't destroyed when inputs are adjusted.

**Comment by Stooberton** [comment]
PR up to fix `WireLib.AdjustOutputs` breaking wirelinks.

https://github.com/wiremod/wire/pull/2314

**Comment by TwistedTail** [comment]
Fixed on https://github.com/wiremod/wire/pull/2314.
