### ISSUE TITLE
[BUG] Invalid Angle

### ISSUE THREAD

**Issue by MozeeRolling** [Stooberton/ACF-3#277]
![unknown](https://user-images.githubusercontent.com/102167935/159508838-7a85d738-9cdd-47c6-831b-fe622fd3c2f1.png)

Short Description

Got this problem on our server. Im spawning Tonk with 30mm RAC, then when im shooting it deals damage only at close range, like 3-5 meters. Interesting thing that every other gun acting absolutely fine.

Branch and Version

Latest master.

Console Error Logs (Optional)

invalid angle in ACF.GetHitAngle
        >HitNormal: 0.000000 0.000000 0.000000, HitDir (BulletVel): -33833.726563 9427.069336 -5144.657715

**Comment by LiddulBOFH** [comment]
I believe this can be closed now?
This PR (https://github.com/Stooberton/ACF-3/commit/699cf9d4c97523db860e72ec98992b993a19ea19) happened a bit after this issue was posted, and I haven't particularly heard or seen this happen on a regular occasion anymore
