### ISSUE TITLE
[BUG] Scalable armor can surpass armor limit set by server owner

### ISSUE THREAD

**Issue by Ally-for-Hire** [Stooberton/ACF-3#279]
**Short Description**

Scalable armor can surpass armor limit set by server owner. Ex: on servers like Valen with a 600mm armor limit you can have 1kmm+ of armor with scalable armor entity

**Branch and Version**

As long as scalable armor has existed idk man

**How to Reproduce (Optional)**

Scalable armor, max the slider, profit

**Comment by OctothorpeObelus** [comment]
This is a pretty simple fix I can do when I get home.

**Comment by Stooberton** [comment]
Is it that simple?
The way armor is calculated on pArmor is through actual line of sight thickness. If we put a cap on one axis, it doesn't stop anyone from making the plate much thicker on another axis and just rotating it.

**Comment by OctothorpeObelus** [comment]
You make a good point there, I'll admit I hadn't considered that, though it wouldn't be very practical for someone to do, as rotating it 90 degrees makes one side dependent on maximum thickness which would mean it could be nullified by the cvar. Not to mention to increased ent count to do it that way.

**Comment by TwistedTail** [comment]
> If we put a cap on one axis, it doesn't stop anyone from making the plate much thicker on another axis and just rotating it.

We could probably just find the thinnest axis and apply the limit on it.

**Comment by homura-akemi-f02-22** [comment]
How about making scalable armour sync better with optical thickness?

**Comment by TwistedTail** [comment]
> How about making scalable armour sync better with optical thickness?

Optical thickness?

> And armour weight too

Scalable armor already uses the volume of the entity and the density of the material to calculate its mass, it should be as accurate as possible already.

**Comment by homura-akemi-f02-22** [comment]
optical thickness as in visual thickness

**Comment by TwistedTail** [comment]
> optical thickness as in visual thickness

That's how it works already, bullets use the actual size of the entity, along with taking into consideration the density of the material to get a RHA equivalent value, to calculate the armor they have to go through whenever they hit a scalable armor plate.

**Comment by homura-akemi-f02-22** [comment]
thanks
