### ISSUE TITLE
[SUGGESTION] Add multi-linking support

### ISSUE THREAD

**Issue by Stooberton** [Stooberton/ACF-3#29]
**Short Description**

Add support for linking multiple entities at once by holding Shift+RClick

**Comment by RedDeadlyCreeper** [comment]
I can work on a prototype tool, I will likely make it a separate tool to also allow multi unlinking or unlinking from all.

**Comment by TwistedTail** [comment]
Added on 7356ae9, merged to master on 40a67db.
