### ISSUE TITLE
[BUG] "Rate of Fire" input on weapons, that do not support the RoF change feature

### ISSUE THREAD

**Issue by juke-cappatalist** [Stooberton/ACF-3#294]
**Short Description**

Basically, the title.
"Rate of Fire" input is present on weapons, that should not have it.

Branch: master
Version: Git-master-a03fd45

![RoF cannon](https://user-images.githubusercontent.com/70792340/172999359-d227aa16-b84d-4c44-bbd8-07b0403d5a0d.png)

**Comment by TwistedTail** [comment]
Fixed on 833be23.
