### ISSUE TITLE
[BUG] Propellant efficiency stored in bulletdata

### ISSUE THREAD

**Issue by LiddulBOFH** [Stooberton/ACF-3#299]
Currently propellant efficiency is being stored post-calculation in bulletdata. Since it is a weapon class specific variable, it should be checked when the weapon is fired, and not stored in the ammo.

It is currently like this: https://github.com/Stooberton/ACF-3/blob/master/lua/acf/shared/ammo/he.lua#L40

And instead it should look at the class of weapon that is firing the round, for the Efficiency variable.

**Comment by TwistedTail** [comment]
Fixed on e6b32c9.
