### ISSUE TITLE
[SUGGESTION] WAV to MP3, redo some sounds

### ISSUE THREAD

**Issue by marchkarcz** [Stooberton/ACF-3#3]
**Short Description**

ACF sounds are a bit dated, WAV files take up a fuckton of space and 320kbps mp3's should sound fine to the majority of people

**Comment by marchkarcz** [comment]
I'll start working on this now

**Comment by marchkarcz** [comment]
MP3's do not loop, possibly redoing sounds could still be done probably but no WAV to MP3

**Comment by Stooberton** [comment]
Most of them aren't looping sounds nor need to loop.

**Comment by marchkarcz** [comment]
Oh wait, yeah true
