### ISSUE TITLE
[BUG] errors after update

### ISSUE THREAD

**Issue by ChorazyTorpeda** [Stooberton/ACF-3#307]
[acf-3-master] addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:10: attempt to call field 'Create' (a nil value)
  1. Create - addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:10
   2. v - addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:40
    3. unknown - lua/includes/modules/hook.lua:96

[acf-3-master] addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:66: attempt to index local 'Entity' (a nil value)
  1. CreatePhysObj - addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:66
   2. GetModelData - addons/acf-3-master/lua/acf/base/model_data/sv_model_data.lua:95
    3. GetModelCenter - addons/acf-3-master/lua/acf/base/model_data/sh_model_data.lua:72
     4. UpdateModel - addons/acf-3-dev/lua/vgui/acf_panel.lua:262
      5. AddModelPreview - addons/acf-3-dev/lua/vgui/acf_panel.lua:315
       6. Action - addons/acf-3-missiles-dev/lua/acf/menu/items_cl/missiles.lua:69
        7. OnNodeSelected - addons/acf-3-dev/lua/acf/menu/spawnmenu_cl.lua:222
         8. OnNodeSelected - lua/vgui/dtree_node.lua:78
          9. OnNodeSelected - lua/vgui/dtree_node.lua:78
           10. OnNodeSelected - lua/vgui/dtree_node.lua:78
            11. SetSelectedItem - lua/vgui/dtree.lua:95
             12. InternalDoClick - lua/vgui/dtree_node.lua:61
              13. DoClick - lua/vgui/dtree_node.lua:33
               14. unknown - lua/vgui/dlabel.lua:237

**Comment by TwistedTail** [comment]
By any chance, did this happen on a singleplayer game?

**Comment by ChorazyTorpeda** [comment]
yes

**Comment by TwistedTail** [comment]
The error points out to a [vanilla Gmod API function](https://wiki.facepunch.com/gmod/ents.Create). Make sure there's no other addon conflicting with it and that your install is not corrupted.
