### ISSUE TITLE
[SUGGESTION] - Official ACF-3 Discord

### ISSUE THREAD

**Issue by LofisisHomeless** [Stooberton/ACF-3#31]
Could have a official ACF-3 Discord where you could easier communicate with the community where people can comfortably talk real time and voice-chat.

**Comment by Stooberton** [comment]
Already thought of that 👍
The invite is at the bottom of the readme.

![image](https://user-images.githubusercontent.com/5084958/72669029-969d9500-39f2-11ea-9045-f43d4e5a0078.png)
