### ISSUE TITLE
Armor indicator Update

### ISSUE THREAD

**Issue by LofisisHomeless** [Stooberton/ACF-3#32]
Addition to the **Armor tool,** its kind of normal for people to snoop around peoples builds, wouldn't it be nice if you could check someone else's total mass without requiring administrator. Implement in a safe way yes.

People always ask how heavy something is but you could always lie about it
This would let you to check peoples HP/T, horse powers and weight without requiring admin. Which is an harmless act that doesn't affect peoples builds.

**Comment by TwistedTail** [comment]
This feature is already being tested on the dev branch.

**Comment by Stooberton** [comment]
See: https://github.com/Stooberton/ACF-3/commit/3b62f8fd29348d28962cd5fbf1d4857998debee7
