### ISSUE TITLE
[BUG] Attempt to call global 'LinkSource' (a nil value)

### ISSUE THREAD

**Issue by ProfessorBoxtrot** [Stooberton/ACF-3#328]
**Short Description**

The above error is produced when trying to use Starfall's :acfAmmoCount() function. Likely due to the fact that LinkSource is not set to ACF.GetLinkSource in `starfall/libs_sv/acffunctions.lua` like it is in `entities/gmod_wire_expression2/core/custom/acffunctions.lua`. AllLinkSources is also undefined.

**Branch and Version**

Master, latest (88b02d6).

**Console Error Logs**

`starfall/libs_sv/acffunctions.lua:2360: attempt to call global 'LinkSource' (a nil value)`

**How to Reproduce**

Spawn an ACF gun and put the following starfall on it:

`chip():isWeldedTo():acfAmmoCount()`

**Comment by TwistedTail** [comment]
Fixed on 2041fca.
