### ISSUE TITLE
[Question] buildmode hooks?

### ISSUE THREAD

**Issue by gmodmurderserver** [Stooberton/ACF-3#330]
**Short Description**

i am wondering how i do it for kyle's buildemode thing for ulx to stop players from taking or doing damage to builders, as i can't find any real examples.

https://steamcommunity.com/sharedfiles/filedetails/?id=1308900979

**Comment by wrefgtzweve** [comment]
https://github.com/Stooberton/ACF-3/blob/1387113c1b8cc3c1c3e348331438a10c58338620/lua/acf/damage/damage_sv.lua#L482

**Comment by TwistedTail** [comment]
Something like [this?](https://github.com/thecraftianman/acf-daktank-buildmode)
