### ISSUE TITLE
[SUGGESTION] Clientside Master Volume

### ISSUE THREAD

**Issue by LofisisHomeless** [Stooberton/ACF-3#34]
Some people find ACF annoying to build beside and it's all sort of noises from
Engines, 1000kg bombs, 140mm, 6x racs autoloaders, 203mm with some 280mm sound file.

It's a quality of life

I'm suggesting a client-side command that lets you adjust the noise level of all ACF instances and events on the map.

Values of the volume would be 0 to 1

0.5 would be 50%

If a master volume isn't possible then maybe try just an on/off by true or false

People can then have a toggle bind on acf volume for their own convenience.

**Comment by TwistedTail** [comment]
For this to be a thing, we'd first need to implement a sound library for ACF so we can have a proper control over the sounds created both server and clientside. I don't see why it shouldn't be a thing once we implement distant sounds, both would take use of the same library.

**Comment by TwistedTail** [comment]
This was partially dealt with on e00a1b7, courtesy of Sparky. There's still some sounds that are played from the server-side, so the client-side volume setting won't affect them.
