### ISSUE TITLE
[BUG] rayMeshIntersect fails when given a spherical entity

### ISSUE THREAD

**Issue by brandonsturgeon** [Stooberton/ACF-3#343]
**Short Description**

I don't fully understand the situation in which this happens, but it's clear that `rayMeshIntersect` fails when given a spherical entity.
This is due to [GetMeshConvexes](https://wiki.facepunch.com/gmod/PhysObj:GetMeshConvexes) returning `nil` when run on a spherical entity's PhysicsObject.

It's _probably_ a simple fix, but I don't understand the importance of this function, so I figured it was best left to the pros 😎

**Branch and Version**
Latest, Stooberton@master

**Console Error Logs (Optional)**

https://github.com/Stooberton/ACF-3/blob/master/lua/acf/core/utilities/util_sh.lua#L276
https://github.com/Stooberton/ACF-3/blob/master/lua/acf/core/utilities/util_sh.lua#L322

![image](https://user-images.githubusercontent.com/7936439/212458800-fbc3847f-0bf9-4872-b198-d59663cd13dd.png)

**Comment by Stooberton** [comment]
Fixed in dfe75fc7c8456f6ec3b0d32edcca1321fde36b17 👍
