### ISSUE TITLE
[SUGGESTION] Something to let you know a sound isn't on the server in the sound replacer

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#347]
After some changes a while ago to fix server console error spam relating to sounds the server doesn't have, I've realized that there's no way to determine whether the server actually has a sound until you put it on an ACF entity and realize it's silent. It would be nice to have either:
- Some kind of warning in the menu if the sound currently selected isn't available on the server
- A fix for the server side error spam that still allows you to use sounds available to your client, but not the server (don't know if this is possible without moving all sounds to the client side)

**Comment by TwistedTail** [comment]
Ideally, #165.
