### ISSUE TITLE
[BUG] World penetration causing intense lag

### ISSUE THREAD

**Issue by LiddulBOFH** [Stooberton/ACF-3#352]
**Short Description**
Was testing changes to a dupe and decided to shoot randomly, and struck a prop_dynamic (road barrier) that was placed just a few feet from the map skybox (gm_goldencity_day), and had a very noticeable hitch in performance. This doesn't extend to hitting regular world brushes, just skybox it seems.

**Branch and Version**
Master, 16F3F4 (6/10/2023)

**Console Error Logs (Optional)**
None available, no errors

**How to Reproduce (Optional)**
Take any weapon and shoot a prop_dynamic thats near a map skybox wall. gm_goldencity has this readily available, as these props are used to mark the edges of the map

Shooting at the barrier directly, facing the skybox wall, note the excessively long traces
This is what causes the lag
![image](https://github.com/Stooberton/ACF-3/assets/13317534/e600710c-bf2b-427b-8ea4-ad4c8f6a5461)
Shooting at the other side of the barrier, into the ground
This does NOT cause lag
![image](https://github.com/Stooberton/ACF-3/assets/13317534/5668c6b1-4ff4-4282-a09f-a32de6975de0)

Yes, I am using SWEPs in these screenshots, however it doesn't make a difference since it fires an ACF bullet, originally ran into this with an ACF machinegun and ACF cannon.

**Comment by BamsTheSergal** [comment]
this also seems to be happening when shooting world doors and custom hammer props
