### ISSUE TITLE
[BUG] WireTable.gmod_wire_expression2 in acf_gun.lua infinite loop

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#36]
The GetUser function is infinite looping somehow. Breaking the loop gives this stacktrace.

addons/acf/lua/entities/acf_gun/init.lua:191: in function 'GetUser'
	addons/acf/lua/entities/acf_gun/init.lua:204: in function <addons/acf/lua/entities/acf_gun/init.lua:195>
	[C]: in function 'xpcall'
	addons/wire/lua/wire/server/wirelib.lua:58: in function 'TriggerInput'
	addons/wire/lua/wire/server/wirelib.lua:530: in function 'TriggerOutput'
	addons/wire/lua/entities/gmod_wire_expression2/init.lua:505: in function 'TriggerOutputs'
	addons/wire/lua/entities/gmod_wire_expression2/init.lua:159: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:13: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:30: in function <entities/gmod_wire_expression2/core/timer.lua:29>

Fixed for now by removing WireTable.gmod_wire_expression2

**Comment by thegrb93** [comment]
Forgot to mention I'm on 928c5d4f7a145537926573719f6e7f538dc3db56

**Comment by TwistedTail** [comment]
It's weird, the stack is referencing an empty line inside gun's ENT:GetUser.

[![Error](https://cdn.discordapp.com/attachments/654142834030542881/676183960522326039/unknown.png)](https://cdn.discordapp.com/attachments/654142834030542881/676183960522326039/unknown.png)

**Comment by thegrb93** [comment]
You're not on 928c5d4f7a145537926573719f6e7f538dc3db56

**Comment by TwistedTail** [comment]
Shouldn't matter, the last time that function was updated was 23 days ago.

**Comment by thegrb93** [comment]
Oh, it's because I removed the `gmod_wire_adv_pod = true,` entries from WireTable

**Comment by thegrb93** [comment]
lua/includes/extensions/entity.lua:23: in function '__index'
	addons/acf/lua/entities/acf_gun/init.lua:183: in function 'GetUser'
	addons/acf/lua/entities/acf_gun/init.lua:208: in function <addons/acf/lua/entities/acf_gun/init.lua:199>
	[C]: in function 'xpcall'
	addons/wire/lua/wire/server/wirelib.lua:58: in function 'TriggerInput'
	addons/wire/lua/wire/server/wirelib.lua:530: in function 'TriggerOutput'
	addons/wire/lua/entities/gmod_wire_expression2/init.lua:505: in function 'TriggerOutputs'
	addons/wire/lua/entities/gmod_wire_expression2/init.lua:159: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:13: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:30: in function <entities/gmod_wire_expression2/core/timer.lua:29>

**Comment by TwistedTail** [comment]
Figured out a way to start an infinite loop with the GetUser function, although the stack it produced on my side doesn't seem to be the same. Give a99e1ab391b9178102e881e4a2bf12a55dc023a0 a shot and tell me if the problem persists.

**Comment by thegrb93** [comment]
Looks like it's fixed. Thanks.
