### ISSUE TITLE
[SUGGESTION] Ammo updating takes too long

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#37]
People are complaining that updating ammo takes ~5 sec? That's pretty inconvenient. Can this be reverted?

**Comment by Assortedark74** [comment]
use acf2 wire functions for guns/ammo, ammo also takes 5+ seconds to update

**Comment by thegrb93** [comment]
Tested myself and it's just the info text is about 0.5s slow to update. I think people are being nitpicky.

**Comment by TwistedTail** [comment]
If you mean the display bubble data, they have an update cooldown of 1 second at most. I can easily change it to be instant if that's the case.

**Comment by thegrb93** [comment]
Yeah, that should help.

**Comment by TwistedTail** [comment]
Changed on 3c3d1c23a161962f912540247381c1dc0db8c1c9, now the info will update instantly when updating an ammo crate.

**Comment by thegrb93** [comment]
Looks fixed. thanks
