### ISSUE TITLE
[BUG] [DEV] New scalable fuel tanks are more than double the mass and capacity that they were previously

### ISSUE THREAD

**Issue by dobriyprop** [Stooberton/ACF-3#379]
**Short Description**

A 24x24x24 fuel tank now weighs 262kg, which seems insanely dense compared to before. Empty mass of the fuel tank is 88kg or so, which also seems incredibly high. Is this intended behavior? This mostly affects lighter vehicles/cars.

**Branch and Version**

Latest dev

**How to Reproduce (Optional)**

Compare any new fuel tank to any old fuel tank of the same size

**Comment by LiddulBOFH** [comment]
There was a magic number for the longest time affecting capacity of fuel tanks which has finally been removed, solely because we now have the exact capacity of fuel tanks due to being scalable.
