### ISSUE TITLE
[BUG] ACF Guns when parented and duped are not able to be read from via wirelink

### ISSUE THREAD

**Issue by LengthenedGradient** [Stooberton/ACF-3#380]
**Short Description**

After parenting and duping and pasting, trying to read any of the gun's outputs via wirelink results in nil. 

I have tested prior and reading from cam controller wirelinks works. It is extremely repeatable, as once I have a dupe of a "broken gun", it will always be unable to be read from no matter how many times you spawn it.

Additionally, I have only observed this issue on guns. Engines do not seem to have this problem, so other ACF entities probably shouldn't be an issue either.

**Branch and Version**

![image](https://github.com/Stooberton/ACF-3/assets/109800352/7c9dbc54-928c-4026-abac-71d9c8436db3)
I should clarify my wiremod and starfall are up to date. I have tested up to date on both singleplayer and multiplayer, with the same results.

**Console Error Logs (Optional)**

No errors were printed to the console

**How to Reproduce (Optional)**

Follow what I did in a recording: (https://www.dropbox.com/scl/fi/vbud6coa93vpovqck7owu/Garry-s-Mod-x64-2023-12-23-23-54-04.mp4?rlkey=5hge1ak705os37vxgj9r9e2f5&dl=0)

**Screenshots (Optional)**

N/A, please check the additional information below

**Additional Information (Optional)**

I've attached a dupe where it occurs, below. In the Starfall chip on the dupe, a program to print out the "Ready" output for the wirelink is present.

[gunbug_001.txt](https://github.com/Stooberton/ACF-3/files/13758172/gunbug_001.txt)

**Comment by thecraftianman** [comment]
Closing because this actually turned out to be a Wiremod bug with saving dupes wired to Create Entity, not an ACF bug
