### ISSUE TITLE
[SUGGESTION] [ACF Survey] More guns.

### ISSUE THREAD

**Issue by DaAstronautical** [Stooberton/ACF-3#4]
**Summary**
More cannons, mortars, and howitzers.

**Raw Suggestions**
The return of the 170, 240, 280 mortar and 290 howitzer.
Recoil-less Rifles
lemme fuckin have my 85s i made pls
Some big guns, bigger than they should be.
More Variety
More of everything
More gun variation like 152mm howtizer
152mm cannon/al
I would like to see bigger explosive weaponry/bigger explosions. Cause nothing is more better then explosive shit.

**Comment by TheWizardLizard** [comment]
i believe i still have an accurately scaled 106mm recoilless rifle

**Comment by Stooberton** [comment]
Outside of recoilless rifles, this has been taken care of by adding scalable weaponry.
