### ISSUE TITLE
[BUG] Still getting version error

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#43]
[ERROR] addons/acf-3/lua/acf/base/version/cl_version.lua:28: attempt to index local 'Version' (a nil value)
  1. GenerateCopy - addons/acf-3/lua/acf/base/version/cl_version.lua:28
   2. func - addons/acf-3/lua/acf/base/version/cl_version.lua:57
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by thegrb93** [comment]
Might be fixed by latest ACF3 missiles update. Will know once the server restarts.

**Comment by TwistedTail** [comment]
That should be the case, now the Version table for each repository is created instantly to prevent any problems related to it not existing.

**Comment by thegrb93** [comment]
Yeah, looks like that fixed it.
