### ISSUE TITLE
[BUG] Some ACF2 dupes spawning with a variety of ammobox-related errors

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#48]
**Short Description**

Not 100% certain what specifically is causing this, but when I spawn some tanks made in ACF2 they spawn bugged ammoboxes that don't undo with the dupe (need to remove them manually with remover tool) alongside some errors in the server console. This also causes CFrame to freak out and spew some errors of its own.

**Console Error Logs**

Refer to screenshots.

**How to Reproduce**

Spawn some old ACF2 tanks, no idea if it's just my tanks somehow.

**Screenshots**

![OBiWz6X](https://user-images.githubusercontent.com/21130637/77187051-3f777780-6aaa-11ea-9720-5354a81c01cb.jpg)
![TCgOTHY](https://user-images.githubusercontent.com/21130637/77187056-40a8a480-6aaa-11ea-9030-933461501d3b.png)
![1assgwn](https://user-images.githubusercontent.com/21130637/77187380-c167a080-6aaa-11ea-9fd9-1fa72889d2ff.png)
![3WT4MwL](https://user-images.githubusercontent.com/21130637/77187656-34711700-6aab-11ea-8029-5779a9562c9a.png)

**Comment by TwistedTail** [comment]
Was that ammo crate using an ammo type that no longer exists?

**Comment by CheezusChrust** [comment]
They might've been but I haven't worked on those tanks for quite a while so I'm not 100% sure.

**Comment by CheezusChrust** [comment]
Had someone spawn a tank that they knew used APDS and it just deleted the ammo boxes using it.

**Comment by TwistedTail** [comment]
Give b516cab a try and tell me if it keeps happening.

**Comment by CheezusChrust** [comment]
Seems to be fixed now.

**Comment by TwistedTail** [comment]
Feel free to reopen the issue if the problem persists.
