### ISSUE TITLE
[BUG] Armor properties tool doesn't account for engines with fuel when calculating HP/ton

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#50]
**Short Description**

The HP/ton rating given by the armor properties tool when pressing reload on a contraption is incorrect if the engine(s) are using fuel. It displays the total HP *without* fuel, and should either show the rating with and without, or detect if fuel is used and display the appropriate rating.

**Comment by Stooberton** [comment]
Resolved in 1c3553c8d067686ed6d9e18625fb4cdee023dac0
