### ISSUE TITLE
[BUG] ACF-2 fuel tanks become disabled on spawn

### ISSUE THREAD

**Issue by TwistedTail** [Stooberton/ACF-3#52]
**Short Description**

Some fuel tanks from ACF-2 dupes might become disabled when they're spawned because their mass is slightly lower than the minimum legal mass.

**Comment by TwistedTail** [comment]
[![Chatlog 1](https://i.imgur.com/uK1MFrl.png)](https://i.imgur.com/uK1MFrl.png)
[![Chatlog 2](https://i.imgur.com/x4MVjx3.png)](https://i.imgur.com/x4MVjx3.png)
[![Chatlog 3](https://i.imgur.com/0t9PFOn.png)](https://i.imgur.com/0t9PFOn.png)

**Comment by TwistedTail** [comment]
Adding a high priority label to this issue as it will cause serious problems with legacy dupes once the addon becomes more widespread.

Any information about which specific fuel tank models have issues will be greatly appreciated as this issue cannot be replicated with freshly spawned dupes and we lack old dupes that use most of the available fuel tank models.

**Comment by TwistedTail** [comment]
Found a similar issue with an ammo crate on one of my old dupes (4x6x8 Crate). Debugging the entity's mass vs its stored ACF legal mass when spawning it from the dupe tells me it should be perfectly legal, so I suppose something being done by GMod after the entity is spawned might be changing its mass again to an old value.

Updating the dupe does fix the issue, and [we've been working on CFrame to prevent cases like this once it gets added into ACF-3](https://github.com/Stooberton/cframe/commit/2daace9c007edc9c69c878aa10052ac4ec7d68d8), so hopefully this issue will sort itself out in the future.

**Comment by Stooberton** [comment]
Appears to have been fixed at some point, can no longer reproduced.

**Comment by TwistedTail** [comment]
Fixed on 863c215. It was due to the mass tool being used on the entity before getting duped.
