### ISSUE TITLE
[BUG] KEshove and HEshove

### ISSUE THREAD

**Issue by PolySteam** [Stooberton/ACF-3#53]
KEShove and HEShove are applying mass relevant to the total mass that has been hit by traces, not total physical mass which is causing HEAT and HE shells to heavily shove vehicles. This gets worse on missiles with their much more potent HEAT shells shoving vehicles at velocities that cause crazyphys to remove them or in the worst case crash the server due to rope like constraints. A probable fix for this would be to convert the parented mass in the shove calc to equiv of physical eg in the case of parented mass being 10000 and physical being 1000 you'd get a ratio of 0.1 as a result of 1000/10000 which the shove from parented props would be multiplied by eg if in this case 7000 of the 10k parented prop mass was shoved, the physical parent would have 700 applied to it.

**Comment by Stooberton** [comment]
Investigated this issue. It appears to originate on the Missiles-side. HEAT/Mass calculations are all working fine in base ACF. Missiles are producing in excess of 34 MJ of energy on impact (a 120 outputs about 13 MJ at the muzzle).

**Comment by TwistedTail** [comment]
A fix was pushed, it was related to the use of a custom function to create ACF Bullets. Give TwistedTail/ACF-3-Missiles@750b283582223f4554be5137d60092269052fc60 a try to check everything's working fine now. If that's the case, I'll close this issue and #46.
