### ISSUE TITLE
[BUG] One of my clients getting version errors

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#56]
[ERROR] addons/acf-3/lua/acf/base/version/cl_version.lua:45: attempt to index local 'Branch' (a nil value)
1. PrintStatus - addons/acf-3/lua/acf/base/version/cl_version.lua:45
2. v - addons/acf-3/lua/acf/base/version/cl_version.lua:63
3. unknown - lua/includes/modules/hook.lua:84

I have the latest ACF-3 but someone is getting these errors. He has acf2 installed on his gmod which idk if that would cause the issue.

**Comment by TwistedTail** [comment]
I honestly don't know how that's even happening, that line will make sure `Branch` isn't nil before using it.

https://github.com/Stooberton/ACF-3/blob/6eea93e252b8de55fc1f13b25c47890105e3317f/lua/acf/base/version/cl_version.lua#L43-L51

**Comment by thegrb93** [comment]
I'm getting the error too. Maybe its related to github's connection issues today?

**Comment by thegrb93** [comment]
Nevermind I wasn't up to date.
