### ISSUE TITLE
[BUG] Version checking not working anymore?

### ISSUE THREAD

**Issue by thegrb93** [Stooberton/ACF-3#59]
In Console:
[ACF - Error] Request unsuccessful (Code 403)
[ACF - Error] Request unsuccessful (Code 403)

In Chat:
[ACF - Updates] ACF-3-Missiles: Server is running on version Git-master-e2d19e0. Unable to check for updates.
[ACF - Updates] ACF-3: Server is running on version Git-master-45beef5. Unable to check for updates.

**Comment by TwistedTail** [comment]
Maybe the server ran out of requests with the Github API? Since the update checker uses unauntheticated requests, the limit will be about 60 requests per hour.
See: https://developer.github.com/v3/#rate-limiting

**Comment by thegrb93** [comment]
Ah ok. thanks
