### ISSUE TITLE
[BUG] Damage Model issue

### ISSUE THREAD

**Issue by Zaroni** [Stooberton/ACF-3#61]
**Short Description**

Damage Model broken regardless of build mode

**more info**

no matter if I have destruction perms set to none, strict or anything in between, props are not able to be damaged.

**Comment by Stooberton** [comment]
Do you have a prop protection addon installed? It's listed as a dependency in the ReadMe. ACF will not function without it.

**Comment by Zaroni** [comment]
> Do you have a prop protection addon installed? It's listed as a dependency in the ReadMe. ACF will not function without it.

I have FPP installed, is there a better one?

**Comment by Zaroni** [comment]
I just installed Nadmod and removed FPP and it works fine, I think this is an issue with FPP, not ACF. this can be resolved.
