### ISSUE TITLE
[BUG] Bullets won't do damage when fired from a gun via e2 wirelink

### ISSUE THREAD

**Issue by PolySteam** [Stooberton/ACF-3#64]
Fire a gun via E2's Wirelink["Fire",number] = 1/acfFire() and the bullets wont do damage. Probably related to inability to get bullet's owner or something similar. This only happens however when the gun itself already has fire wired to something, using E2 to fire the gun wont inflict any damage when the bullets impact.

**Comment by TwistedTail** [comment]
On guns, `ENT:GetUser()` was missing an IsValid check for cases like empty pod controllers that'd return a NULL entity as their driver. Fixed on 31a8de6.
