### ISSUE TITLE
[BUG] Decals spazz out like crazy when shooting at large entities

### ISSUE THREAD

**Issue by BamsTheSergal** [Stooberton/ACF-3#65]
basically, when a gun shoots at a large lfs plane, it creates large decals onto them and stretches very big as seen below in the screenshot, (i uninstalled acf3 just so i could show this better), and while testing it i crashed from it. 
![hl2_H0sfaLibpT](https://user-images.githubusercontent.com/12705993/84526529-162e4800-aca3-11ea-9ff7-2a2dbefb5150.png)

**Comment by TwistedTail** [comment]
I've noticed decals stretch out against certain models, causing them to display more than one "impact". For reference, these are two impacts, one from a 100mm cannon and another one from a 12.7mm machinegun.
![Multiple impacts](https://puu.sh/FVDgD/39ed872aa4.png)

Although, this is the first time I've seen them stretching out of the model like that, or even crashing the server. I'm gonna try to solve this issue I mentioned above with decals and see if that fixes your issue, in the meantime you could also ask the LFS dev about it. Impact decals on ACF-3 are applied using `util.DecalEx`, so it'd be possible for them to test this behavior aswell and maybe see if it's a fault on their side.

**Comment by BamsTheSergal** [comment]
no, the server didn't crash, but i did. and i could try talking to luna.

**Comment by TwistedTail** [comment]
Any news on this issue?

**Comment by BamsTheSergal** [comment]
it seems to be fixed, and i wasn't able to see it happen since reporting it.
