### ISSUE TITLE
[BUG] Debris cause server crashes

### ISSUE THREAD

**Issue by Stooberton** [Stooberton/ACF-3#66]
**Short Description**

Debris tend to crash servers and show up often with being removed by crazyphysics. It's most likely caused by excessive force being applied to them in certain scenarios.

**How to Reproduce (Optional)**

Kill props with ACF. Large explosions would probably provide more energy, but large caliber (energy) AP kills might cause it as well.

**Additional Information (Optional)**
This can probably be fixed by tweaking values here:

https://github.com/Stooberton/ACF-3/blob/dev/lua/acf/server/damage.lua#L611
https://github.com/Stooberton/ACF-3/blob/dev/lua/acf/server/damage.lua#L647

**Comment by shadow7483147** [comment]
Why does debris need to be serverside, anyways? Can't we just make it a clientside prop?

**Comment by Stooberton** [comment]
> #109 an attempt was made

Merged.
