### ISSUE TITLE
[BUG] Semiautos have incorrect accuracy 

### ISSUE THREAD

**Issue by Amplar** [Stooberton/ACF-3#68]
Semiautos currently have 1.1 spread, when their acf2 default was  0.1.
For reference, HMGs are 1.3, and autocannons are 0.12. They are currently less useful than a shotgun.

Semiautos are meant to be limited magazine, high rate of fire, accurate weapons for lighter vehicles.

**Comment by Stooberton** [comment]
Addressed in b7c4fa5ebe4093235ae013f34e2abbec82efc61d
