### ISSUE TITLE
[SUGGESTION] Gun breech remodel (for cannons)

### ISSUE THREAD

**Issue by TheMrFailz** [Stooberton/ACF-3#7]
Gun breeches are insanely long as of right now which makes fitting otherwise reasonable cannons for certain tanks (in some cases even their historical guns) incredibly difficult. As far as I can tell the worst offenders are the bigger calibers like 120's and up. Short barrel cannon breeches are significantly closer to what they should be.

In short: cut short barrel breech off, graft onto long barrel cannon.

**Comment by almo-anth** [comment]
I agree we need to substantially revamp the size of ACF cannon breeches

**Comment by TwistedTail** [comment]
Closing, implemented on 335ebed96b17cc4ac17b714fdb808e1ebe96e1d2.
