### ISSUE TITLE
[BUG] ACF_Check function fails to create ACF table on entities

### ISSUE THREAD

**Issue by TwistedTail** [Stooberton/ACF-3#71]
**Short Description**

One of the problems I've noticed on the servers is that `ACF_Check` will eventually start failing to check people's props. This will lead to dupes getting broken since the ACF table on entities will never be created, leading to stuff like armor setting to error and fail.

**Console Error Logs**

`Error applying entity modifer, "acfsettings". ERROR: addons/acf-3/lua/weapons/gmod_tool/stools/acfarmorprop.lua:105: attempt to index field 'ACF' (a nil value) (x3)`

**How to Reproduce (Optional)**

It's really hard to replicate, it usually happens when the server has been up for too long. Although, it seems to affect a single player in specific, despite these checks are done server-side.

**Comment by Amplar** [comment]
I was wondering why I couldn't set the armor of some things. I also found props armored incorrectly, or not armored at all (I assume it's because it failed to armor and I did not notice)

**Comment by TwistedTail** [comment]
This problem seems to only affect entities that use the generic spawn function, as it only seems to be produced on props.

**Comment by TwistedTail** [comment]
Almost 2 years and this issue hasn't appeared again, closing.
