### ISSUE TITLE
what in the fuck is this fuel consumption

### ISSUE THREAD

**Issue by norrbotten** [Stooberton/ACF-3#72]
my heli which BEFORE the last fuel update lasted about 15 minutes, which was already pretty bad, now has fuel for about 2 minutes of flight, having realistic fuel and speed figures mind you

what in the fuck is this, reverting to an older branch on my servers

**Comment by Stooberton** [comment]
See #70 on "Fuel consumption far too low".

> This was addressed in [4305e8a](https://github.com/Stooberton/ACF-3/commit/4305e8a3d7aba2d295bd05abf41dbca7f6f6bd63), with fuel consumption being increased by 27.8 times.
> 
> A tank built with a 120mm cannon, 30 rounds of ammo, an ACF pod, some autocannon ammo, a large V12 and transmissions consumes less than half the volume of an actual tank with the same specifications. Therefore, fuel consumption was increased to encourage about 1000L of fuel, under the assumption that tanks drive around for 5 to 15 minutes, in order to consume the remaining volume necessary to be "real tank" size.

ACF is not about helicopters, planes, or cars. Any and all support for them is completely secondary to AFVs. This decision was made to better influence vehicle design, which is currently atrocious.

If you enjoy doorstopper tanks in your server, by all means revert. ACF will continue in pursuit of more balanced and fun gameplay.

**Comment by norrbotten** [comment]
ok i will revert to acf2 🙃

**Comment by TwistedTail** [comment]
Addressed on 156cca4a28, servers with `acf_gamemode` set to 1 will use the old fuel consumption, while servers with it set to 0 will require no fuel at all. It's called the development branch for a reason, nothing is really definitive until it makes it to master, and even then it can be changed.
