### ISSUE TITLE
[SUGGESTION] Add fuel consumption modifier as a server local

### ISSUE THREAD

**Issue by Goodva** [Stooberton/ACF-3#73]
Not everyone was happy with recent fuel consumption nerf, so let the server owner decide if vehicle really needs 800 liters of fuel to function for over 7 minutes or not.

**Comment by TwistedTail** [comment]
Addressed on 156cca4a28. You can either:
- Set the server's `acf_gamemode` to 1 (Classic), in which case engines will use the old fuel consumption OR
- Play around with `acf_fuelrate` console variable.
