### ISSUE TITLE
[BUG] Infinite gearbox loop causing instant server crash

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#8]
How to reproduce:

- Link two inline (or any number of other types) gearboxes together in an infinite loop
- Attach an engine to the loop
- Turn on the engine
- Congratulations, you've crashed the server!

![image](https://user-images.githubusercontent.com/21130637/70741792-1fd1f580-1cea-11ea-8081-30e2285366c5.png)

**Comment by Stooberton** [comment]
Solved by #14
