### ISSUE TITLE
[BUG] Flare ammobox explosions are disproportionately large compared to other ammo types

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#89]
**Short Description**

Flare ammobox explosions will literally take up the entire map if set up "properly".

**How to Reproduce (Optional)**

Spawn a flare ammo box with 140SB as the weapon type. Max out the crate size, the projectile length, and the dual spectrum filler. Blow up the ammo box. You've now smoked the *entire map*, and it'll linger for a good 2-3 minutes.

For comparison, an identical sized ammo box containing maximum boom 140SB HE rounds makes an explosion roughly 50-75m in diameter.

**Screenshots (Optional)**

![ezgif-2-a5f5fda24edd](https://user-images.githubusercontent.com/21130637/88492479-0c258780-cf79-11ea-9307-b0ae0fce1d96.gif)

**Comment by TwistedTail** [comment]
Turns out, flare ammo had 5 times the amount of filler mass than similar ammo types. Fixed on 3a4f942, the explosion shouldn't be bigger than the one produced by other ammo crates.
