### ISSUE TITLE
[BUG] Scalable ammo crates reset size on server freeze

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#90]
**Short Description**

When the server freezes, the disconnect timer starts, and then unfreezes it resets the size of every scalable ammo crate currently spawned to 24x24x24 and they lose their hitbox so you can't grab it with the physgun or hit it with the toolgun.

**How to Reproduce (Optional)**

_Freeze the server with your desired method_ until the disconnect timer shows up and then wait for the server to unfreeze. 

**Screenshots (Optional)**
https://youtu.be/otzK2y7LP3s

**Comment by TwistedTail** [comment]
It's most likely the client-side entity being removed/affected (See: https://github.com/Facepunch/garrysmod-issues/issues/3184). Gonna have to see if there's a way to detect this event on the server-side and force it to send a full update to each client.

**Comment by TwistedTail** [comment]
There might be a chance I fixed this issue by accident on a38def7, depending on what Gmod/Source do in the event of high server lag with client-side entities. I haven't been able to confirm this myself though.

**Comment by TwistedTail** [comment]
Fixed on 102ff80, entities using the base_scalable entity as their base will be forced to re-scale on the client-side whenever a full update happens.
