### ISSUE TITLE
[BUG] ACF Links aren't considered as a contraption

### ISSUE THREAD

**Issue by shadow7483147** [Stooberton/ACF-3#91]
When using tools that lookup throughout an entire contraption, ACF links don't get detected as being "contraption links."

Granted, this is hardly an issue considering most ACF ents will already be constrained or parented to a contraption in another way, but it would help enforce consistency with tool behavior.

Reproduction:

1. Spawn a gun
2. Spawn an ammo box
3. Link them together
4. Right click with remover tool
5. Whichever ent is hit gets removed, the other stays

Intended behavior:

4. Right click with remover tool
5. All linked entities are removed

**Comment by Stooberton** [comment]
As far as I can tell there's no way to achieve this without highly intrusive hacks. Would quite likely interfere with many other addons and aspects of ACF.

Unless someone wants to work on this themselves, this isn't going to be investigated or worked on.
