### ISSUE TITLE
[BUG] Armor values change when duped

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#92]
**Short Description**

When you put an ACF armor value on a prop, dupe it, and spawn it at a later date there's a chance that the armor value will change by up to ±10mm. This happens with both parented and physical props.

**How to Reproduce (Optional)**
It doesn't happen every time, but it seems that when you dupe something with ACF armor and then spawn it at a later date there is a chance that the armor value will change

**Screenshots (Optional)**
https://i.imgur.com/tSCwn8z.png
Was 250 ^

https://i.imgur.com/QuoNdc4.png
Was 350 ^

**Comment by shadow7483147** [comment]
In your second screenshot, the health of the entity is lowered from 92 down to 15. Assuming it's the exact same model, it's likely something to do with ductility. Remember, lower duct props have better armor for mass, but less HP after penetration.

**Comment by DynamX767** [comment]
Btw just as clarification, those are 2 separate props and are in no way related to each other. I was simply posting those pictures to show that it was affecting multiple props. They are not the same prop

**Comment by TwistedTail** [comment]
Tried to replicate this a few times, is there any specific model or entity that does this more consistently?

**Comment by DynamX767** [comment]
No, I haven't been able to reliably replicate it. I only notice that it happens sometimes when I paste a dupe.
