### ISSUE TITLE
[BUG] Gearboxes don't output any power after being updated until their gear is changed

### ISSUE THREAD

**Issue by CheezusChrust** [Stooberton/ACF-3#95]
**Short Description**

When an ACF gearbox/differential/transfer case gets updated, I'd say about 75% of the time it gets put into a state where it says it's in gear 1, but doesn't output any torque. This can either be fixed by switching gears up and back down, or duping and respawning the vehicle.

**How to Reproduce**

Update a gearbox/transfer case/diff on a vehicle a few times, and try to actually use it without changing gears.

**Comment by TwistedTail** [comment]
Fixed on 4ec8fc7. Not gonna close this issue instantly, but as far as I could see they're now updating properly.
