### ISSUE TITLE
[BUG] Scalable ammo boxes not having a proper hitbox

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#98]
**Short Description**
When a scalable ammo box is created with the size of 12x12x12 it doesn't have a proper hitbox with the tool gun. Details about the ammo can't be viewed and you don't get a snapping grid on it, although the toolgun can still technically interact with it.

**How to Reproduce (Optional)**

Make an ammobox that is 12x12x12 and look at it with the toolgun

**Screenshots (Optional)**

https://i.imgur.com/KIewAqd.gif

**Comment by TwistedTail** [comment]
Fixed on f0cda64. It was related to ENT:GetSize returning the original size if ENT.Size wasn't defined, which is the case when the entity is first spawned. Since the new size and the original size were the same, scaling would be omitted.
