### ISSUE TITLE
[BUG] APDS/APFSDS Ammo causes cannon reload to be significantly shorter than other ammo types. 

### ISSUE THREAD

**Issue by LeninCat** [Stooberton/ACF-3#99]
**Short Description**

APDS/APFSDS Ammo causes cannon reload to be significantly shorter than other ammo types. (Excluding Flechette)

**Additional Information**

With commit https://github.com/Stooberton/ACF-3/commit/07d9370671e5109bc686a3270aaf8ad81e32945d. 
changes to apds and apfsds ammo projectile weight caused reload of cannons to be twice as fast or some times 3 times as fast.

**Comment by Stooberton** [comment]
Issue stems from APFSDS being unusually light, as cartridge mass is how reload times are calculated.

![image](https://user-images.githubusercontent.com/5084958/89453380-ca3cd400-d724-11ea-8038-98fca28e5910.png) ![image](https://user-images.githubusercontent.com/5084958/89453400-d163e200-d724-11ea-81e2-95e0f49c3e9a.png)

**Comment by Dakota0001** [comment]
APFSDS *should* be about twice as fast or better to load than full AP if we're going from a realism standpoint, though in the pictures you posted APFSDS is lighter than it should be and AP is slightly heavier than it should be.

M829A1 being 20.9 kg and for AP from a 120mm cannon of L/60 length the complete round would be 48.8 KG. Though the projectile in this case would be only 23.1 kg compared to the 50% heavier 36.66 kg. That said the rounds are editable anyway in ACF but it might be something to look into. 

Source:
https://i.imgur.com/kCn2Ry1.png

**Comment by Stooberton** [comment]
I don't see an issue with APFSDS firing faster as it deals significantly less damage. I'm looking to see what numbers can be tweaked to get better times and, failing that, I'm thinking of having the cartridge length have an affect on reload time.

**Comment by Stooberton** [comment]
Part of the discrepancy comes from the difference in projectile material. In ACF, darts are currently made of steel with a density 7.9g/cm3 versus tungsten's 19.3.  This checks out with M829s projectile being about twice the weight with roughly the same dart length.

**Comment by Stooberton** [comment]
Reload times addressed in 12a385e4e8491a1c6eb7c32f8ca3be949583b3e7
Ammunition weights and performance addressed in 4130eb92d1d1480ed7e9ac722c471776f07a7312

Adjusted propellant density and propellant energy output to achieve appropriate cartridge weight and approximate penetration and muzzle velocity of actual rounds.

![image](https://user-images.githubusercontent.com/5084958/89463018-e72cd380-d733-11ea-9173-0255250ad2e6.png)![image](https://user-images.githubusercontent.com/5084958/89463032-edbb4b00-d733-11ea-9469-667b1c00cfdc.png)

Incorporated total projectile length into reload time calculations to normalize reload times of similar sized cartridges with catridge mass contributing to 2/3s of the total reload time and total length the last 1/3. Currently works out to a 120 AP reloading in 8.6 seconds (down from 10.3) and 120 APFSDS loading in 4.6 seconds (up from 2.8).

The proportions and values can be tweaked as needed.
